// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';


const SUPABASE_URL = "https://etopnfupwrtkwgpqlhzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0b3BuZnVwd3J0a3dncHFsaHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2OTA5NTYsImV4cCI6MjA1MzI2Njk1Nn0.G7kFCWyjZv0S9k0YarF0ct-cYuTLP1fw5R4pXY_Qu48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);